CREATE TABLE [dbo].[Bill]
(
	[ID] NVARCHAR(128) NOT NULL PRIMARY KEY, 
    [CreatedDate] DATETIME2 NOT NULL DEFAULT getutcdate(), 
	[ShopId] int NOT NULL,
	[Total] MONEY NOT NULL,
	[Paid] MONEY NOT NULL,
	[Change] Money NOT NULL,
    [UserId] NVARCHAR(128) NOT NULL FOREIGN KEY REFERENCES [User](ID) 
)
